services:
  # ----------------------------
  # MESSAGING INFRASTRUCTURE
  # ----------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-tier

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - app-tier

  # Web UI to view Kafka Topics (Access at http://localhost:8080)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8090"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - app-tier

  # ----------------------------
  # DATABASE INFRASTRUCTURE
  # ----------------------------
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my@test@Pass12
      POSTGRES_DB: ticket_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-tier

  # Web UI to view Database (Access at http://localhost:8978)
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    depends_on:
      - postgres
    ports:
      # Default CloudBeaver web port
      - "8978:8978"
    environment:
      # Optional: set initial config for Postgres connection (Internal Network)
      CLOUDBEAVER_DRIVER: postgres-jdbc
      CLOUDBEAVER_URL: jdbc:postgresql://postgres:5432/ticket_db
      CLOUDBEAVER_USER: admin
      CLOUDBEAVER_PASSWORD: my@test@Pass12
    volumes:
      # Recommended for persistence of CloudBeaver settings
      - cloudbeaver_workspace:/opt/cloudbeaver/workspace
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  postgres_data:
  cloudbeaver_workspace: # New volume for CloudBeaver data