spring:
  application:
    name: email-ticket-system

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_db
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect